### ISSUE TITLE
Issues in plotter when using networkx release candidates

### ISSUE THREAD

**Issue by yampelo** [graphistry/pygraphistry#127]
https://github.com/graphistry/pygraphistry/blob/fe62057b239430e0339269ae991d04bb08a176c7/graphistry/plotter.py#L429

this line errors when using a release candidate of networkx. For example 2.3rc2 gives:

```
2019-06-02T13:50:54 | beagle.web.api.views.new:334 | DEBUG | Traceback (most recent call last):
  File "/Users/yampelo/dev/beagle/beagle/web/api/views.py", line 328, in new
    G = graph.graph()
  File "/Users/yampelo/dev/beagle/beagle/backends/graphistry.py", line 109, in graph
    ).plot(G, render=self.render)
  File "/Users/yampelo/.envs/beagle-yfNwRKYV/lib/python3.6/site-packages/graphistry/plotter.py", line 326, in plot
    dataset = self._plot_dispatch(g, n, name, 'json')
  File "/Users/yampelo/.envs/beagle-yfNwRKYV/lib/python3.6/site-packages/graphistry/plotter.py", line 489, in _plot_dispatch
    (e, n) = self.networkx2pandas(graph)
  File "/Users/yampelo/.envs/beagle-yfNwRKYV/lib/python3.6/site-packages/graphistry/plotter.py", line 448, in networkx2pandas
    self.networkx_checkoverlap(g)
  File "/Users/yampelo/.envs/beagle-yfNwRKYV/lib/python3.6/site-packages/graphistry/plotter.py", line 428, in networkx_checkoverlap
    [x, y] = [int(x) for x in nx.__version__.split('.')]
  File "/Users/yampelo/.envs/beagle-yfNwRKYV/lib/python3.6/site-packages/graphistry/plotter.py", line 428, in <listcomp>
    [x, y] = [int(x) for x in nx.__version__.split('.')]
ValueError: invalid literal for int() with base 10: '3rc3'
```

**Comment by lmeyerov** [comment]
Thanks. NetworkX has been making backwards incompatible changes so we're currently locked on an old version.

Maybe we separate out NetworkX Old vs NetworkX New, or ignore Old entirely?

Also a good argument to push more on a pluggable system here.
