### ISSUE TITLE
[BUG] `CONTAINS(...)` filters cause server error if NULL values 

### ISSUE THREAD

**Issue by DBCerigo** [graphistry/pygraphistry#301]
**Describe the bug**
Applying a `CONTAINS(some_attribute, "some_substring")` filter to an attribute that contains NULL values (`None` or `np.nan` in the dataframes used for graph creation) causes a (presumed) internal server error - UI shows `Herding stray GPUs...` then requests to reload. 

**To Reproduce**
Example graph: https://hub.graphistry.com/graph/graph.html?dataset=cb1d727659684c74bb64195e1881d1f9
Working example: filter with `CONTAINS(edge:attribute_1, "foo") -> works as expected
Breaking example: filter with `CONTAINS(point:attribute_1, "a") -> `Herding stray GPUs...`

**Expected behavior**
Filtering using `CONTAINS()` with NULL values in attribute should just filter out those NULL values and not break.

**Actual behavior**
`Herding stray GPUs`

**Screenshots**
See graph example above. 

**Browser environment (please complete the following information):**
 - OS: PopOS
 - Browser: Firefox 

**Graphistry GPU server environment**
- Graphistry hosted

**Comment by lmeyerov** [comment]
@DBCerigo Thank you!

Corresponding service trace, suggesting a parser issue:

```
streamgl-viz_1         | 2022-01-21T21:37:23.352536823Z {"level":20,"time":1642801043352,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/core/viz/src/worker/services/dataframe/maskDataframe.js","payload":{},"msg":"@services::maskDataframe"}
streamgl-viz_1         | 2022-01-21T21:37:23.353802647Z {"level":20,"time":1642801043353,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/core/viz/src/worker/simulator/expressionCodeGenerator.js","payload":{"astType":"FunctionCall","source":"(function (value) { return (value.indexOf(\"a\") !== -1); })"},"msg":"Evaluating (single-column)"}
streamgl-viz_1         | 2022-01-21T21:37:23.353980681Z {"level":20,"time":1642801043353,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/core/viz/src/worker/simulator/expressionCodeGenerator.js","payload":{"ast":{"type":"FunctionCall","callee":{"type":"FunctionIdentifier","name":"CONTAINS"},"arguments":[{"type":"Identifier","name":"point:attribute_1"},{"type":"Literal","dataType":"string","value":"a"}]},"bindings":{"*":"value"},"source":"(function (value) { return (value.indexOf(\"a\") !== -1); })"},"msg":"////functionForAst"}
streamgl-viz_1         | 2022-01-21T21:37:23.353981362Z {"level":20,"time":1642801043353,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/core/viz/src/worker/simulator/expressionCodeGenerator.js","payload":{"astType":"Identifier","source":"(function (value) { return value; })"},"msg":"Evaluating (single-column)"}
streamgl-viz_1         | 2022-01-21T21:37:23.353981603Z {"level":20,"time":1642801043353,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/core/viz/src/worker/simulator/expressionCodeGenerator.js","payload":{"ast":{"type":"Identifier","name":"point:attribute_1"},"bindings":{"*":"value"},"source":"(function (value) { return value; })"},"msg":"////functionForAst"}
streamgl-viz_1         | 2022-01-21T21:37:23.354143857Z {"level":20,"time":1642801043354,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/core/viz/src/worker/simulator/expressionCodeGenerator.js","payload":{"astType":"FunctionCall","source":"(function (value) { return (value.indexOf(\"a\") !== -1); })"},"msg":"Evaluating (single-column)"}
streamgl-viz_1         | 2022-01-21T21:37:23.354183559Z {"level":20,"time":1642801043354,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/core/viz/src/worker/simulator/expressionCodeGenerator.js","payload":{"ast":{"type":"FunctionCall","callee":{"type":"FunctionIdentifier","name":"CONTAINS"},"arguments":[{"type":"Identifier","name":"point:attribute_1"},{"type":"Literal","dataType":"string","value":"a"}]},"bindings":{"*":"value"},"source":"(function (value) { return (value.indexOf(\"a\") !== -1); })"},"msg":"////functionForAst"}
streamgl-viz_1         | 2022-01-21T21:37:23.354384989Z {"level":50,"time":1642801043354,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/core/viz/src/worker/simulator/Dataframe.js","payload":{"msg":"=== BAD getMasksForQuery","e":{},"query":{"ast":{"type":"FunctionCall","callee":{"type":"FunctionIdentifier","name":"CONTAINS"},"arguments":[{"type":"Identifier","name":"point:attribute_1"},{"type":"Literal","dataType":"string","value":"a"}]},"error":null,"type":"point","attribute":"point:attribute_1"},"attribute":"attribute_1","type":"point"}}
streamgl-viz_1         | 2022-01-21T21:37:23.354869769Z {"level":50,"time":1642801043354,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/core/viz/src/worker/simulator/Dataframe.js","msg":"{\n  ast: {\n    type: \u001b[32m'FunctionCall'\u001b[39m,\n    callee: { type: \u001b[32m'FunctionIdentifier'\u001b[39m, name: \u001b[32m'CONTAINS'\u001b[39m },\n    arguments: [\n      { type: \u001b[32m'Identifier'\u001b[39m, name: \u001b[32m'point:attribute_1'\u001b[39m },\n      { type: \u001b[32m'Literal'\u001b[39m, dataType: \u001b[32m'string'\u001b[39m, value: \u001b[32m'a'\u001b[39m },\n      [length]: \u001b[33m2\u001b[39m\n    ]\n  },\n  error: \u001b[1mnull\u001b[22m,\n  type: \u001b[32m'point'\u001b[39m,\n  attribute: \u001b[32m'point:attribute_1'\u001b[39m\n}"}
streamgl-viz_1         | 2022-01-21T21:37:23.355811058Z {
streamgl-viz_1         | 2022-01-21T21:37:23.355815957Z   msg: '=== BAD getMasksForQuery',
streamgl-viz_1         | 2022-01-21T21:37:23.355816288Z   e: TypeError: Cannot read property 'indexOf' of null
streamgl-viz_1         | 2022-01-21T21:37:23.355816759Z       at eval (eval at functionForAST (/opt/graphistry/apps/core/viz/src/worker/simulator/expressionCodeGenerator.js:382:33), <anonymous>:1:35)
streamgl-viz_1         | 2022-01-21T21:37:23.355816919Z       at Dataframe._59b‍.r.Dataframe.getMaskForPredicateOnAttributeValues (/opt/graphistry/apps/core/viz/src/worker/simulator/Dataframe.js:328:24)
streamgl-viz_1         | 2022-01-21T21:37:23.355817370Z       at Dataframe._59b‍.r.Dataframe.getAttributeMask (/opt/graphistry/apps/core/viz/src/worker/simulator/Dataframe.js:347:24)
streamgl-viz_1         | 2022-01-21T21:37:23.355817510Z       at Dataframe._59b‍.r.Dataframe.getMasksForQuery (/opt/graphistry/apps/core/viz/src/worker/simulator/Dataframe.js:259:26)
streamgl-viz_1         | 2022-01-21T21:37:23.355817761Z       at groupExpressionsByTypeWithLimitsAndErrors (/opt/graphistry/apps/core/viz/src/worker/services/dataframe/maskDataframe.js:285:33)
streamgl-viz_1         | 2022-01-21T21:37:23.355817921Z       at /opt/graphistry/apps/core/viz/src/worker/services/dataframe/maskDataframe.js:53:19
streamgl-viz_1         | 2022-01-21T21:37:23.355818843Z       at maskDataframe (/opt/graphistry/apps/core/viz/src/worker/services/dataframe/maskDataframe.js:190:7)
streamgl-viz_1         | 2022-01-21T21:37:23.355819063Z       at MergeMapSubscriber.project (/opt/graphistry/apps/core/viz/src/schema/expressions.js:51:35)
streamgl-viz_1         | 2022-01-21T21:37:23.355819274Z       at MergeMapSubscriber._tryNext (/opt/graphistry/node_modules/rxjs/operator/mergeMap.js:120:27)
streamgl-viz_1         | 2022-01-21T21:37:23.355819494Z       at MergeMapSubscriber._next (/opt/graphistry/node_modules/rxjs/operator/mergeMap.js:110:18)
streamgl-viz_1         | 2022-01-21T21:37:23.355819634Z       at MergeMapSubscriber.Subscriber.next (/opt/graphistry/node_modules/rxjs/Subscriber.js:89:18)
streamgl-viz_1         | 2022-01-21T21:37:23.355819875Z       at FilterSubscriber._next (/opt/graphistry/node_modules/rxjs/operator/filter.js:87:30)
streamgl-viz_1         | 2022-01-21T21:37:23.355820115Z       at FilterSubscriber.Subscriber.next (/opt/graphistry/node_modules/rxjs/Subscriber.js:89:18)
streamgl-viz_1         | 2022-01-21T21:37:23.355820356Z       at ReduceSubscriber._complete (/opt/graphistry/node_modules/rxjs/operator/reduce.js:119:30)
streamgl-viz_1         | 2022-01-21T21:37:23.355821157Z       at ReduceSubscriber.Subscriber.complete (/opt/graphistry/node_modules/rxjs/Subscriber.js:114:18)
streamgl-viz_1         | 2022-01-21T21:37:23.355821528Z       at MergeMapSubscriber.notifyComplete (/opt/graphistry/node_modules/rxjs/operator/mergeMap.js:165:30)
streamgl-viz_1         | 2022-01-21T21:37:23.355821899Z       at InnerSubscriber._complete (/opt/graphistry/node_modules/rxjs/InnerSubscriber.js:30:21)
streamgl-viz_1         | 2022-01-21T21:37:23.355822510Z       at InnerSubscriber.Subscriber.complete (/opt/graphistry/node_modules/rxjs/Subscriber.js:114:18)
streamgl-viz_1         | 2022-01-21T21:37:23.355822790Z       at MapSubscriber.Subscriber._complete (/opt/graphistry/node_modules/rxjs/Subscriber.js:132:26)
streamgl-viz_1         | 2022-01-21T21:37:23.355823151Z       at MapSubscriber.Subscriber.complete (/opt/graphistry/node_modules/rxjs/Subscriber.js:114:18)
streamgl-viz_1         | 2022-01-21T21:37:23.355823692Z       at MergeMapSubscriber._complete (/opt/graphistry/node_modules/rxjs/operator/mergeMap.js:135:30)
streamgl-viz_1         | 2022-01-21T21:37:23.355823933Z       at MergeMapSubscriber.Subscriber.complete (/opt/graphistry/node_modules/rxjs/Subscriber.js:114:18)
streamgl-viz_1         | 2022-01-21T21:37:23.355824213Z       at MergeMapSubscriber.notifyComplete (/opt/graphistry/node_modules/rxjs/operator/mergeMap.js:165:30)
streamgl-viz_1         | 2022-01-21T21:37:23.355824373Z       at InnerSubscriber._complete (/opt/graphistry/node_modules/rxjs/InnerSubscriber.js:30:21)
streamgl-viz_1         | 2022-01-21T21:37:23.355824674Z       at InnerSubscriber.Subscriber.complete (/opt/graphistry/node_modules/rxjs/Subscriber.js:114:18)
streamgl-viz_1         | 2022-01-21T21:37:23.355824905Z       at MergeMapSubscriber.notifyComplete (/opt/graphistry/node_modules/rxjs/operator/mergeMap.js:165:30)
streamgl-viz_1         | 2022-01-21T21:37:23.355825155Z       at InnerSubscriber._complete (/opt/graphistry/node_modules/rxjs/InnerSubscriber.js:30:21)
streamgl-viz_1         | 2022-01-21T21:37:23.355825295Z       at InnerSubscriber.Subscriber.complete (/opt/graphistry/node_modules/rxjs/Subscriber.js:114:18)
streamgl-viz_1         | 2022-01-21T21:37:23.355825556Z       at /opt/graphistry/node_modules/rxjs/util/subscribeToResult.js:37:29
streamgl-viz_1         | 2022-01-21T21:37:23.355825716Z       at runMicrotasks (<anonymous>)
streamgl-viz_1         | 2022-01-21T21:37:23.355826387Z       at processTicksAndRejections (internal/process/task_queues.js:95:5),
streamgl-viz_1         | 2022-01-21T21:37:23.355826638Z   query: {
streamgl-viz_1         | 2022-01-21T21:37:23.355826808Z     ast: { type: 'FunctionCall', callee: [Object], arguments: [Array] },
streamgl-viz_1         | 2022-01-21T21:37:23.355827049Z     error: null,
streamgl-viz_1         | 2022-01-21T21:37:23.355827189Z     type: 'point',
streamgl-viz_1         | 2022-01-21T21:37:23.355827429Z     attribute: 'point:attribute_1'
streamgl-viz_1         | 2022-01-21T21:37:23.355827670Z   },
streamgl-viz_1         | 2022-01-21T21:37:23.355827991Z   attribute: 'attribute_1',
streamgl-viz_1         | 2022-01-21T21:37:23.355828151Z   type: 'point'
streamgl-viz_1         | 2022-01-21T21:37:23.355836087Z }
streamgl-viz_1         | 2022-01-21T21:37:23.355871325Z {
streamgl-viz_1         | 2022-01-21T21:37:23.355871756Z   ast: {
streamgl-viz_1         | 2022-01-21T21:37:23.355871976Z     type: 'FunctionCall',
streamgl-viz_1         | 2022-01-21T21:37:23.355872307Z     callee: { type: 'FunctionIdentifier', name: 'CONTAINS' },
streamgl-viz_1         | 2022-01-21T21:37:23.355872548Z     arguments: [
streamgl-viz_1         | 2022-01-21T21:37:23.355872758Z       { type: 'Identifier', name: 'point:attribute_1' },
streamgl-viz_1         | 2022-01-21T21:37:23.355873169Z       { type: 'Literal', dataType: 'string', value: 'a' },
streamgl-viz_1         | 2022-01-21T21:37:23.355873309Z       [length]: 2
streamgl-viz_1         | 2022-01-21T21:37:23.355873449Z     ]
streamgl-viz_1         | 2022-01-21T21:37:23.355873730Z   },
streamgl-viz_1         | 2022-01-21T21:37:23.355873990Z   error: null,
streamgl-viz_1         | 2022-01-21T21:37:23.355874211Z   type: 'point',
streamgl-viz_1         | 2022-01-21T21:37:23.355874441Z   attribute: 'point:attribute_1'
streamgl-viz_1         | 2022-01-21T21:37:23.355874652Z }
streamgl-viz_1         | 2022-01-21T21:37:23.356085685Z {"level":20,"time":1642801043355,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/lib/instrumentation/got.js","msg":"making got request: POST http://nginx/streamgl/read/node?id=e20292480b224b3dae471c9c81480daf"}
streamgl-viz_1         | 2022-01-21T21:37:23.356086396Z {"level":20,"time":1642801043356,"pid":7279,"hostname":"da8e63a2d355","filename":"/opt/graphistry/apps/lib/instrumentation/got.js","msg":"making got request: POST http://nginx/streamgl/read/edge?id=e20292480b224b3dae471c9c81480daf"}
streamgl-viz_1         | 2022-01-21T21:37:23.357115606Z {"level":50,"time":1642801043356,"pid":7279,"hostname":"da8e63a2d355","payload":["Cannot read property 'indexOf' of null"],"msg":"unhandledRejection"}
streamgl-viz_1         | 2022-01-21T21:37:23.357286100Z You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
streamgl-viz_1         | 2022-01-21T21:37:23.357288034Z Cannot read property 'indexOf' of null
```

The likely `indexOf` bytecode is:

https://github.com/graphistry/graphistry/blob/1e823200d40529a5e5f8c39e4d173fa00373edc7/apps/core/viz/src/worker/simulator/expressionCodeGenerator.js#L268

The fix seems to be an null/undefined check

**Comment by lmeyerov** [comment]
Fixed: `CONTAINS(point:attribute_1, "a") ` now works in 2.38.11

Already live on Hub, and will be in the next enterprise release as well

This and a few related methods were missing a dynamic check, now added. Thanks!
