### ISSUE TITLE
is_sso_login not working as expected, errors with: Exception: 'str' object has no attribute 'xframe_options_exempt' 

### ISSUE THREAD

**Issue by DataBoyTX** [graphistry/pygraphistry#510]
**Describe the bug**
when I try to access a Graphistry server with site-wide SSO enabled, I get the following error: `Exception: 'str' object has no attribute 'xframe_options_exempt'`
 
Also, curious what is meant by the text in the output `enter SSO login` ?

```
$ python
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import graphistry
>>> graphistry.__version__
'0.29.5'
>>> graphistry.register(api=3, protocol="https", server="test-2-40-35", is_sso_login=True)
No username/password, personal key id/secret & token provided, enter SSO login
Login to site wide SSO
Error: <Response [200]>
Traceback (most recent call last):
  File "/home/tcook/miniconda/lib/python3.10/site-packages/graphistry/arrow_uploader.py", line 307, in sso_login
    raise Exception(json_response['message'])
Exception: 'str' object has no attribute 'xframe_options_exempt'Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tcook/miniconda/lib/python3.10/site-packages/graphistry/pygraphistry.py", line 693, in register
    PyGraphistry.sso_login(org_name, idp_name, sso_timeout=sso_timeout)
  File "/home/tcook/miniconda/lib/python3.10/site-packages/graphistry/pygraphistry.py", line 232, in sso_login
    ).sso_login(org_name, idp_name)
  File "/home/tcook/miniconda/lib/python3.10/site-packages/graphistry/arrow_uploader.py", line 307, in sso_login
    raise Exception(json_response['message'])
Exception: 'str' object has no attribute 'xframe_options_exempt'
>>>
```
same error in jupyter as command line above..

Also, adding a username, results in the following error: (should I open a different ticket on this? 

```
$ python
Python 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import graphistry
>>> graphistry.__version__
'0.29.5'
>>> graphistry.register(api=3, protocol="https", server="test-2-40-35a.grph.xyz", username="tcook@graphistry.com", is_sso_login=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tcook/miniconda/lib/python3.10/site-packages/graphistry/pygraphistry.py", line 680, in register
    raise Exception(MSG_REGISTER_MISSING_PASSWORD)
Exception: Error: username exists but missing password
>>>
```

**Expected behavior**
I expected it to launch an SSO dialog in the browser

**PyGraphistry API client environment**
 - Where run:, Graphistry 2.40.35.9 Jupyter + cmdline 
 - Version: 2.40.35
 - Python Version: 3.10

**Comment by lmeyerov** [comment]
Confirmed bug in nexus that came in during embedded SSO support, tracking internally (fix already in progress)

**Comment by lmeyerov** [comment]
I think this is fixed, closing 

cc @DataBoyTX if not
